public enum UIType : byte
{
    TitleUI,
    InventoryUI,
    PetInfoUI,
    TopUI,
    MainUI,
    PlayerHudUI,
    QuestHudUI,
    PopupUI,
    MapUI,
    DialogueUI,
    MainMenuUI,
    ResourceHudUIView,
    PartyHudUIView,
    VillageInfoHudUIView,
    InventoryUIView,
    SkillHudUIView,
    QuestDetailUIView,
    PetInventoryUIView,
    PlayerHudUIView,
    ConvoyHudUIView,
    LevelUpUIView,
    LoadingUIView,
    ScreenFadeUIView,
    SimplePopupUIView,
    ConvoySuccessUIView,
    ConvoyFailUIView,
    WagonAreaWarningUIView,
    UltimateSelectUIView,
    MagicCircleUIView,
}

public enum UIRootType : byte
{
    Background,
    Main,
    Content,
    Popup,
    Front
}
